### ISSUE TITLE
statusLocation in WPS response is incorrectly encoded

### ISSUE THREAD

**Issue by jkburges** [aodn/geoserver#4]
The URL given in the `statusLocation` has URL encoded `&`s, whereas I *think* that it should not.

e.g.: 
`statusLocation="http://geoserver-systest.aodn.org.au/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=cb59205d-6222-4c65-a1b0-c7a706f86c56"` 

should be 

`statusLocation="http://geoserver-systest.aodn.org.au/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionStatus&executionId=cb59205d-6222-4c65-a1b0-c7a706f86c56"`

**Comment by danfruehauf** [comment]
Is that what comes back in the XML response?

**Comment by jkburges** [comment]
> Is that what comes back in the XML response?

Correct.  An example response in its entirety:

```xml
<?xml version="1.0"?>
<wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" statusLocation="http://geoserver-systest.aodn.org.au/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=279ad502-23bd-4628-bfdb-ffa52c1fe5fd" serviceInstance="http://geoserver-systest.aodn.org.au/geoserver/ows?" service="WPS" xml:lang="en" version="1.0.0">
  <wps:Process wps:processVersion="1.0.0">
    <ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">gs:NetcdfOutput</ows:Identifier>
    <ows:Title xmlns:ows="http://www.opengis.net/ows/1.1">NetCDF download</ows:Title>
    <ows:Abstract xmlns:ows="http://www.opengis.net/ows/1.1">Subset and download collection as NetCDF files</ows:Abstract>
  </wps:Process>
  <wps:Status creationTime="2015-09-22T03:49:06.443Z">
    <wps:ProcessAccepted>Process accepted.</wps:ProcessAccepted>
  </wps:Status>
</wps:ExecuteResponse>
```

**Comment by danfruehauf** [comment]
Aren't `&`s supposed to be encoded in XML?

**Comment by jkburges** [comment]
Yeah, actually, what's happening is correct.
